DigitalPortfolio/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path

from .views import *
from .tests import TestView

urlpatterns = [
    path('', index, name='home'),
    path('test/', TestView.as_view(), name='test'),
    path('register/', register, name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('enter-email/', EnterEmailToResetPassword.as_view(), name='enter_email'),
    path('set-new-password/<uidb64>/<token>/', UserResetPasswordConfirm.as_view(), name='reset_password'),
    path('stream_video/<int:pk>/', get_streaming_video, name='stream_video'),
    # path('plug_stream_video', get_streaming_video_plug, name='plug_stream_video'),

    path('profile:<slug:nickname>/eidt-settings-account', EditAccountInformationView.as_view(), name='edit_settings_account'),
    path('profile:<slug:nickname>/edit-settings-profile', EditProfileView.as_view(), name='edit_settings_profile'),
    path('profile:<slug:nickname>/edit-settings-security', EditSecuritySettingsView.as_view(), name='edit_settings_security'),
    path('profile:<slug:nickname>/edit-settings-tags', EditProfileTagsView.as_view(), name='edit_settings_tags'),

    path('profile:<slug:nickname>/create-post', CreatePostView.as_view(), name='create_post'),
    path('profile:<slug:nickname>/', UserProfileView.as_view(), name='view_user_profile'),
    path('profile:edit-post:<slug:post_slug>', EditPostView.as_view(), name='edit_post'),
    path('profile:edit-post-tags:<slug:post_slug>', EditPostTagsView.as_view(), name='edit_post_tags'),
    path('profile:favorites-posts', ProfileFavouritePostsView.as_view(), name='favorites_posts'),
    path('profile:favorites-users', ProfileFavouriteUsersView.as_view(), name='favorites_users'),

    path('delete-post:<int:post_id>', delete_post, name='delete_post'),
    path('like-post:<int:post_id>', like_post, name='like_post'),
    path('dislike-post:<int:post_id>', dislike_post, name='dislike_post'),

    path('search:post', SearchPostView.as_view(), name='search_post'),
    path('search:user', SearchUserView.as_view(), name='search_user'),

    path('page-guides', GuidesView.as_view(), name='view_guides'),
]

portfolio/models.py
import os
from datetime import date

from PIL import Image
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.timezone import now
from unidecode import unidecode

from .choices import *
from .utils import SOCIAL_NETWORKS, get_path_to_post_files


def filter_tags(tags):
    res = []
    for tag in tags:
        if tag.__str__() not in ("None", ""):
            res.append(tag)
    return res


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    patronymic = models.CharField(max_length=50, blank=True, verbose_name='Отчество')
    date_of_birth = models.DateField(verbose_name='Дата рождения')
    nickname = models.SlugField(max_length=50, unique=True, verbose_name='Никнейм')
    text = models.TextField(blank=True, verbose_name='Описание профиля')
    image = models.ImageField(upload_to='photos/avatars', null=True, verbose_name='Фото профиля')
    phone_number = models.CharField(max_length=15, blank=True, verbose_name='Номер телефона')
    city = models.ForeignKey('City', null=True, on_delete=models.PROTECT, verbose_name='Город')
    scope_of_work = models.CharField(max_length=20, choices=JOB_SPHERE_CHOICES, blank=True,
                                     verbose_name='Сфера деятельности')
    experience = models.CharField(max_length=20, choices=EXPERIENCE_CHOICES, blank=True,
                                  verbose_name='Опыт работы')
    specialization = models.CharField(max_length=40, choices=SPECIALIZATION_CHOICES, blank=True,
                                      verbose_name='Специализация')
    employment_type = models.ManyToManyField('ProfileEmploymentType', verbose_name='Тип занятости')
    work_schedule = models.ManyToManyField('ProfileWorkSchedule', verbose_name='График работы')
    skills = models.ManyToManyField('ProfileSkill', verbose_name='Ключевые навыки')

    def get_tags(self):
        tags = (self.experience, self.specialization)
        return filter_tags(tags)

    def get_user_age(self):
        today = date.today()
        return today.year - self.date_of_birth.year - (
                (today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))

    def save(self, *args, **kwargs):
        if not self.nickname and self.user.username:
            self.nickname = slugify(self.user.username)
        super().save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)

            if img.height > 500 or img.width > 500:
                output_size = (500, 500)
                img.thumbnail(output_size)
                img.save(self.image.path)

    def __str__(self):
        return f'{self.user.last_name} {self.user.first_name} {self.patronymic}'

    def get_absolute_url(self):
        return reverse('view_user_profile', kwargs={'nickname': self.nickname})

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ['user__last_name', 'user__first_name', 'patronymic']


class ProfileSocialNetwork(models.Model):
    type = models.CharField(choices=[(sn, sn) for sn in SOCIAL_NETWORKS.keys()], max_length=50)
    link = models.URLField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='social_networks')

    def get_image_url(self):
        if self.type in SOCIAL_NETWORKS.keys():
            path = SOCIAL_NETWORKS[self.type]
            return path
        return ''


class StrMixin:
    def __str__(self):
        return self.name


class ProfileSkill(StrMixin, models.Model):
    name = models.CharField(max_length=50, choices=SKILLS_CHOICES, unique=True)


class ProfileEmploymentType(StrMixin, models.Model):
    name = models.CharField(max_length=30, choices=EMPLOYMENT_TYPE_CHOICES, unique=True)


class ProfileWorkSchedule(StrMixin, models.Model):
    name = models.CharField(max_length=30, choices=WORK_SCHEDULE_CHOICES, unique=True)


class City(models.Model):
    name = models.CharField(max_length=50, unique=True)
    country = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['country', 'name']


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    post_slug = models.SlugField(db_index=True, unique=True)
    title = models.CharField(max_length=120, verbose_name='Заголовок')
    text = models.TextField(max_length=700, blank=True, verbose_name='Описание')
    date = models.DateField(default=now, verbose_name='Дата')
    created_at = models.DateTimeField(auto_now_add=True)
    budget = models.CharField(max_length=50, blank=True, choices=BUDGET, verbose_name='Бюджет в рублях')
    post_type = models.CharField(choices=PROJECT_TYPE_CHOICES, blank=True, max_length=50, verbose_name='Тип поста')
    genre = models.CharField(choices=PROJECT_GENRE_CHOICES, max_length=64, blank=True, verbose_name='Жанр')
    music_genre = models.CharField(max_length=30, blank=True, choices=MUSIC_GENRE_CHOICES, verbose_name='Жанр музыки')
    style = models.CharField(choices=STYLE_CHOICES, blank=True, max_length=64, verbose_name='Стиль')
    age_limit = models.CharField(max_length=3, blank=True, choices=AGE_LIMITS, verbose_name='Возрастное ограничение')
    rhythm = models.ForeignKey('PostRhythm', null=True, on_delete=models.PROTECT, related_name='posts',
                               verbose_name='Ритм')
    count_likes = models.IntegerField(default=0, verbose_name='Лайки')
    liked_users = models.ManyToManyField(User, related_name='liked_posts')

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if not self.post_slug:
            self.post_slug = slugify(unidecode(self.title))
        super().save(*args, **kwargs)

    def is_liked_post(self, user) -> bool:
        result = self.liked_users.contains(user)
        return result

    def get_count_likes(self):
        return self.liked_users.count()

    def get_tags(self):
        tags = (self.rhythm, self.music_genre, self.style, self.genre, self.age_limit, self.budget)
        return filter_tags(tags)


class PostPhoto(models.Model):
    file = models.ImageField(upload_to=get_path_to_post_files)
    post = models.ForeignKey(Post, related_name='photos', on_delete=models.CASCADE)


class PostVideo(models.Model):
    formats = ['mp4']
    file = models.FileField(upload_to=get_path_to_post_files, validators=[FileExtensionValidator(formats)])
    preview = models.ImageField(upload_to=get_path_to_post_files)
    post = models.ForeignKey(Post, related_name='videos', on_delete=models.CASCADE)


class PostFile(models.Model):
    formats = ['pdf', 'ppt', 'pptx', 'doc', 'docx']
    file = models.FileField(upload_to=get_path_to_post_files,
                            validators=[FileExtensionValidator(formats)])
    post = models.ForeignKey(Post, related_name='files', on_delete=models.CASCADE)

    def __str__(self):
        return os.path.basename(self.file.name)


class PostRhythm(StrMixin, models.Model):
    name = models.CharField(max_length=30, unique=True, choices=RHYTHM_CHOICES, verbose_name='Ритм')
    description = models.CharField(max_length=100, verbose_name='Описание ритма')

    def get_description(self):
        return self.description

portfolio/templates/portfolio/base/base-edit-post.html
{% extends 'portfolio/base/base-with-navigation.html' %}

{% block main %}
    {% block post-form %}
    {% endblock %}
    <section class="settings-items">
        <ul>
            {% if post_is_created %}
                <li class="post-edit"><a href="{% url 'edit_post' post.post_slug %}">Редактирование поста</a></li>
                <li class="tags"><a href="{% url 'edit_post_tags' post.post_slug %}">Выбор тегов</a></li>
            {% else %}
                <li class="post-edit">Редактирование поста</li>
                <li class="tags">Выбор тегов</li>
            {% endif %}
        </ul>
    </section>
{% endblock %}

portfolio/templates/portfolio/base/base-search.html
{% extends 'portfolio/base/base-with-navigation.html' %}
{% load static %}
{% block style_load %}
   
    <link rel="stylesheet" href="{% static 'portfolio/css/checkselect.css' %}" />
    {% block search_style_load %}
    {% endblock search_style_load %}
{% endblock %}
{% block search_block %}
    <button type="button" id="show-params-btn">Параметры</button>
    <form>
        {{ form }}
        <button type="submit" class="search-button">Поиск</button>
        <button type="submit" class="search-image">
            <img src="{% static 'portfolio/images/search-image.png' %}">
        </button>
    </form>
{% endblock search_block %}
{% block main %}
    {% block search %}{% endblock %}
    <section class="settings-items">
        <nav>
            <ul>
                <li class="user-search">
                    <a href="{% url 'search_user' %}">Поиск пользователей</a>
                </li>
                <li class="post-search">
                    <a href="{% url 'search_post' %}">Поиск постов</a>
                </li>
            </ul>
        </nav>
    </section>
    <script src="https://snipp.ru/cdn/jquery/2.1.1/jquery.min.js"></script>
    <script src="{% static 'portfolio/js/checkselect.js' %}"></script>
    <script src="{% static 'portfolio/js/form.js' %}"></script>
{% endblock %}

portfolio/templates/portfolio/base/base-settings.html
{% extends 'portfolio/base/base-with-navigation.html' %}
{% load static %}

{% block main %}

    {% block settings %}
    {% endblock %}

    <section class="settings-items">
        <nav>
            {% with user_profile.nickname as nickname %}
            <ul>
                <li class="account">
                    <a href="{% url 'edit_settings_account' nickname %}">Аккаунт</a>
                    <img src="{% static "portfolio/images/account icon.svg" %}" alt="Account icon"/>
                </li>
                <li class="infromation">
                    <a href="{% url 'edit_settings_profile' nickname %}">Информация профиля</a>
                    <img src="{% static "portfolio/images/infromation icon.svg" %}" alt="Infromation icon"/>
                </li>
                <li class="security">
                    <a href="{% url 'edit_settings_security' nickname %}">Безопасность</a>
                    <img src="{% static "portfolio/images/security icon.svg" %}" alt="Security icon"/>
                </li>
                <li class="tags">
                    <a href="{% url 'edit_settings_tags' nickname %}">Теги пользователя</a>
                    <img src="{% static "portfolio/images/tag.svg" %}" alt="Tag icon"/>
                </li>
            </ul>
                {% endwith %}
        </nav>
    </section>
{% endblock %}

portfolio/templates/portfolio/base/base-with-navigation.html
{% extends 'portfolio/base/base.html' %}
{% load static %}
{% block site-navigation %}
    {% block search_block %}
    {% endblock search_block %}
    <div class="profile-settings">
        <a href="{% url 'search_user' %}" class="icon-search">
            <img src="{% static 'portfolio/images/search-icon.svg' %}"
                 alt="Иконка поиска" />
        </a>
        {% if request.user.is_authenticated %}
            <a href="{{ request.user.profile.get_absolute_url }}"
               class="profile-icon">
                <img src="{% static 'portfolio/images/profile icon.svg' %} "
                     alt="Иконка профиля" />
            </a>
            <div class="window">
                <a href="{% url 'favorites_posts' %}">
                    <div>
                        <p>Избранное</p>
                        <img src="{% static 'portfolio/images/mark.svg' %}">
                    </div>
                </a>
                <a href="{% url 'view_guides' %}">
                    <div>
                        <p>Гайды</p>
                        <img src="{% static 'portfolio/images/book.svg' %}">
                    </div>
                </a>
                <a href="{% url 'logout' %}">
                    <div>
                        <p>Выйти</p>
                        <img src="{% static 'portfolio/images/exit.svg' %}">
                    </div>
                </a>
            </div>
            <a href="{% url "edit_settings_account" request.user.profile.nickname %}"
               class="settings-icon">
                <img src="{% static 'portfolio/images/settings icon.png' %} "
                     alt="Иконка настроек" />
            </a>
        </div>
    {% else %}
        <div class="no-login">
            <a href="{% url 'login' %}">Войти /</a>
            <a href="{% url 'register' %}">Зарегистрироваться</a>
        </div>
    {% endif %}
{% endblock %}

portfolio/templates/portfolio/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'portfolio/css/header-footer.css' %} "/>
    {% block style_load %}
    {% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
    <style>
        ol {
            list-style-type: none;
        }
    </style>
</head>
<body>

<header class="main-header">
    {% include 'portfolio/base/logo.html' %}
    {% block site-navigation %}
    {% endblock %}
</header>

<main>
    <h1>{{ title }}</h1>
    {% block main %}
    {% endblock %}
</main>

<footer class="main-footer">
    {% include 'portfolio/base/logo.html' %}
</footer>
</body>
</html>

portfolio/templates/portfolio/base/logo.html
{% load static %}

<a href="{% url 'search_post' %}">
    <img src="{% static 'portfolio/images/Share your projects.svg' %} " alt="Share your projects">
</a>

portfolio/templates/portfolio/base/post.html
{% load static %}
{% load portfolio_tags %}

<div class="post">
    <div class="photo">
        {% if user_profile.image %}
            <img src="{{ post.author.profile.image.url }}" alt="Фото профиля">
        {% else %}
            <img src="{% static 'portfolio/images/profileNO.png' %}" alt="Фото профиля">
        {% endif %}
    </div>
    <div class="post-information">
        {% if post.title %}
            <p class="post-name">{{ post.title }}</p>
        {% endif %}
        {% if post.post_type %}
            <p class="post-type">{{ post.post_type }}</p>
        {% endif %}
        <div class="tags">
            {% for tag in post.get_tags %}
                <p>{{ tag }}</p>
            {% endfor %}
        </div>
        {% with post.photos.all as photos %}
            {% with post.videos.all as videos %}
                {% if photos or videos %}
                    <section class="post-image">
                        <button class="slide-arrow slide-arrow-prev" id="slide-arrow-prev">
                            &#8249;
                        </button>
                        <button class="slide-arrow slide-arrow-next" id="slide-arrow-next">
                            &#8250;
                        </button>
                        <ul class="slides-container" id="slides-container"> 
                            {% for photo in photos %}
                                <li class="slide">
                                    <div id="img-viewer">
                                        <img class="modal-content close" id="full-image" onclick="close_model()">
                                    </div>
                                    <img class="user-image img-source expand-icon" src="{{ photo.file.url }}"
                                         onclick="full_view(this);">
                                </li>
                            
                            {% endfor %}

                            {% for video in videos %}
                                <li class="slide video-slide ">
                                    <div>
                                        
                                        <img class="user-image img-source expand-icon" src="{{ video.preview.url }}">
                                        <img class="playTriangle" src={% static 'portfolio/images/triangleBlue.png' %} onclick="playVideo('{{ video.pk }}')">
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                        
                    </section>
                    
                {% endif %}
            {% endwith %}
        {% endwith %}

        {#        {% if post.text %}#}
        {#            <p class="post-description">{{ post.text }}</p>#}
        {#        {% endif %}#}
        {#        {% if post.date %}#}
        {#            <p class="date">{{ post.date }}</p>#}
        {#        {% endif %}#}
        {#        {% if post.genre %}#}
        {#            <p>Жанр: {{ post.get_genre_display }}</p>#}
        {#        {% endif %}#}
        {#        {% if post.style %}#}
        {#            <p>Стиль: {{ post.style }}</p>#}
        {#        {% endif %}#}
        {#        {% if post.budget %}#}
        {#            <p>Бюджет: {{ post.budget }}</p>#}
        {#        {% endif %}#}
        {#        {% if post.age_limit %}#}
        {#            <p>Возрастные ограничения: {{ post.age_limit }}</p>#}
        {#        {% endif %}#}
        {% if post.files %}
            <div class="script">
                {% for user_file in post.files.all %}
                    <a href="{{ user_file.file.url }}" download="{{ user_file }}">
                        <img src="{% static 'portfolio/images/file.png' %}" alt="{{ user_file.file.name }}">
                        <p>{{ user_file }}</p>
                        <img class="right" src="{% static 'portfolio/images/post-arrow-right.svg' %}" width="14"
                             height="20"
                             alt="Стрелка вправо">
                    </a>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    {% if post.author == request.user %}
        <div class="icons">
            <button type="button" class="favourites">
                <img src="{% static 'portfolio/images/three dorts.png' %}" alt="Настройки">
            </button>
            <div class="post-menu">
                <ul>
                    <li class="edit"><a href="{% url 'edit_post' post.post_slug %}">Редактировать пост</a></li>
                    <li class="edit"><a href="{% url 'delete_post' post.pk %}">Удалить пост</a></li>
                </ul>
            </div>
        </div>
    {% endif %}
    <div class="like">
        <p>{{ post.get_count_likes }}</p>
        {% if request.user.is_authenticated and request.user != post.author %}
            {% is_liked post request.user as liked %}
            {% if liked %}
                <a href="{% url 'dislike_post' post.pk %}">
                    <img src="{% static 'portfolio/images/hurtRED.png' %}" alt="Красное сердечко">
                </a>
            {% else %}
                <a href="{% url 'like_post' post.pk %}">
                    <img src="{% static 'portfolio/images/hurtEMPTY.png' %}" alt="Пустое сердечко">
                </a>
            {% endif %}
        {% else %}
            <a href="#">
                <img src="{% static 'portfolio/images/hurtRED.png' %}" alt="Сердечко">
            </a>
        {% endif %}
    </div>
</div>

portfolio/templates/portfolio/base/video-player.html
{% load static %}
{% block style_load %}
    <link href="https://vjs.zencdn.net/8.10.0/video-js.css" rel="stylesheet"/>
{% endblock %}
<div class="video-player" style="display: none">
    <video
            id="video-player"
            class="video-js"
            controls
            preload="none"
            width="640"
            height="264"
            data-setup="{}"
          
    >
        {# Заглушка обязательна! Иначе плеер не будет работать #}
        <source src="{% static 'portfolio/video/plug-video.mp4' %}?t={{ timestamp }}" type="video/mp4"/>

        <p class="vjs-no-js">
            To view this video please enable JavaScript, and consider upgrading to a
            web browser that
            <a href="https://videojs.com/html5-video-support/" target="_blank"
            >supports HTML5 video</a
            >
        </p>
       
       
    </video>
    <button class="krest" onclick="closeVideoPlayer()">X</button>
</div>

<script src="https://vjs.zencdn.net/8.10.0/video.min.js"></script>
<script src="{% static 'portfolio/js/video-player.js' %}"></script>